# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.1
#osx_image: xcode8
language: objective-c
env:
  global:
  - COMMIT_AUTHOR_EMAIL: "antonis.tsakiridis@telestax.com"

# Consider uncommenting this once we are stable
# cache: cocoapods
podfile: Test-App/Podfile
before_install:
- openssl aes-256-cbc -K $encrypted_1a2b91771659_key -iv $encrypted_1a2b91771659_iv -in ~\/.ssh/github_rsa.enc -out ~\/.ssh/github_rsa -d
# Add the key to the ssh agent
- ssh-add ~\/.ssh/github_rsa
#- travis_wait 60 pod repo update > /dev/null 2>&1
#- travis_wait 60 ./pod-repo-update.sh

#- gem install cocoapods # Since Travis is not always on latest version
#- travis_wait 60 pod repo update --silent
- pod install --project-directory=Test-App
script:
#- set -o pipefail && xcodebuild test -workspace Test-App/Sample.xcworkspace -scheme Sample -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- set -o pipefail && xcodebuild test -workspace Test-App/Sample.xcworkspace -scheme Sample -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' | xcpretty
#- set -o pipefail && xcodebuild test -workspace Test-App/Sample.xcworkspace -scheme Sample -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.1'
#- set -o pipefail && xcodebuild test -workspace Test-App/Sample.xcworkspace -scheme Sample -destination 'platform=iOS Simulator,name=iPhone SE'
- set -o pipefail && travis_retry xcodebuild test -workspace Test-App/Sample.xcworkspace -scheme Sample -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0' | xcpretty
- ./scripts/main.bash
